version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:19.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd
           git clone --depth=1 https://github.com/Panchajanya1999/msm-4.14.git -b $CIRCLE_BRANCH
           cd msm-4.14
           git clone https://github.com/Panchajanya1999/myscripts.git -b master
           source myscripts/kernel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
